---
- name: Restart Keepalived
  service:
    name: keepalived
    state: restarted

- name: Systemctl daemon-reload
  shell: "systemctl daemon-reload"

- name: Restart keepalived-exporter
  service:
    name: prometheus-keepalived-exporter
    state: restarted