---
- name: HAProxy Package
  apt:
    name: haproxy

- name: HAProxy cfg
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - Restart HAProxy

- name: HAProxy exporter
  docker_container: 
    name: haproxy_exporter 
    image: quay.io/prometheus/haproxy-exporter:v0.9.0 
    state: started
    restart_policy: always
    ports: 
      - 9101:9101 
    command: --haproxy.scrape-uri="http://172.17.0.1:88/haproxy?stats;csv"

- name: HAProxy servicized
  service:
    name: haproxy
    state: started
    enabled: yes