---
- name: Collect info about all VMs
  hosts: all
  become: yes
  roles:
    - init
    - users

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind
    - bind_exporter
  tags:
    - bind

- name: Resolvers (etc/resolv.conf - resolvers etc. etc.)
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - hosts_dns
  tags:
    - resolver

- name: Prometheus
  hosts: prometheus_server
  become: yes
  gather_facts: no
  roles:
    - prometheus
  tags:
    - prometheus
