---
- name: Collect info about all VMs
  hosts: all
  tasks:
    - setup:

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind9

- name: adding dns server to hosts (resolv.conf)
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - hosts_dns