---
- name: Collect info about all VMs
  hosts: all
  become: yes
  roles:
    - init

- name: Prometheus
  hosts: prometheus_server
  become: yes
  gather_facts: no
  roles:
    - prometheus
  tags:
    - prometheus

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind
  tags:
    - bind

- name: Resolvers
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - hosts_dns
  tags:
    - resolvers

- name: Nginx, reverse proxy, node exporter
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - nginx
    - reverse_proxy
    - nginx_exporter
  tags:
    - nginx
    - proxy

- name: Bind exporter
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind_exporter
  tags:
    - bind_exporter

- name: MySQL
  hosts: mysql_servers
  become: yes
  gather_facts: no
  roles:
    - mysql
    - mysql_exporter
  tags:
    - mysql

- name: General monitoring
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - rsyslog
  tags:
    - rsyslog

- name: Influx database
  hosts: influxdb
  become: yes
  gather_facts: no
  roles:
    - influxdb
  tags:
    - influxdb

- name: Pinger service
  hosts: pinger
  become: yes
  gather_facts: no
  roles:
    - pinger
  tags:
    - pinger

- name: Docker 
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - docker
  tags:
    - docker

- name: Agama docker
  hosts: docker_agama
  become: yes
  gather_facts: no
  roles:
    - agama_docker
  tags:
    - agama

- name: Grafana docker
  hosts: docker_grafana
  become: yes
  gather_facts: no
  roles:
    - grafana_docker
  tags:
    - grafana

- name: HAProxy
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - haproxy
  tags:
    - haproxy

- name: Keepalived
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - keepalived
  tags:
    - keepalived

- name: Backup
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - backup
  tags:
    - backup