---
- name: Collect info about all VMs
  hosts: all
  tasks:
    - setup:

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind

- name: Nginx and node exporter
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - nginx
  tags:
    - nginx
    - node_exporters

- name: adding dns server to hosts (resolv.conf)
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - hosts_dns

- name: prometheus
  hosts: prometheus_server
  become: yes
  gather_facts: no
  roles:
    - prometheus