- name: Install uwsgi
  apt:
    name: uwsgi

- name: Install python uwsgi plugin
  apt:
    name: uwsgi-plugin-python3

- name: Get uwsgi config file
  copy:
    src: /home/jul/infra-labs/03-web-app/roles/uwsgi/files/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '0755'
  notify: Restart uwsgi
  
- name: Ensure that uwsgi runs and it starts on sysem boot
  service: 
    name: uwsgi
    enabled: yes
    state: started

     
