---
- name: install fping
  apt:
    name: fping

- name: Group for pinger user
  group:
    name: pinger
    state: present

- name: Pinger user
  user:
    name: pinger
    comment: pinger service
    group: pinger

- name: Script
  template:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    owner: pinger
    group: pinger
    mode: '0755'

- name: Create directory for pinger conf
  file: path=/etc/pinger state=directory mode=0755

- name: Script config file
  template:
    src: pinger.conf
    dest: /etc/pinger/pinger.conf
  notify:
    - Systemctl daemon-reload
    - Restart pinger

- name: Servisizing
  template:
    src: pinger.service
    dest: /etc/systemd/system/pinger.service
  notify:
    - Systemctl daemon-reload
    - Restart pinger

- name: Start on boot
  service:
    name: pinger
    state: started
    enabled: yes