---
- name: Get agama image
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama
    mode: '0755'
    
- name: Create image
  docker_image:
    name: agama
    build:
      path: /opt/agama
      network: host
    source: build

- name: Agama container
  docker_container:
    name: agama
    image: agama
    published_ports:
      - "{{ agama_docker_port }}:8000"
    env:
      AGAMA_DATABASE_URI: 'mysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}'
    state: started