- name: Installing mysql
  apt: 
    name: mysql-server
    state: latest

- name: installing mysql-python module
  apt:
    name: 
      - python3-pymysql
      - python3-mysqldb
    state: present

- name: MySQL service 
  service:
    name: mysql
    state: started
    enabled: yes

- name: Adding new cnfg file for mysql
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Mysql restart

- name: Create MySQL database
  mysql_db:
    name: "{{ mysql_database }}"

- name: Create database user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    state: present
    host: "%"

- name: Add replciation user for MySQL
  mysql_user:
    name: replication
    host: "%"
    password: "{{ replication_user_pass }}"
    priv: "*.*:REPLICATION SLAVE"
    login_unix_socket: /var/run/mysqld/mysqld.sock
