---
- name: Install prometheus
  apt:
    name: prometheus

- name: prometheus arguments
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Prometheus restart

- name: prometheus conf file (target machines)
  template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Prometheus restart

- name: Ensure prometheus starts
  service:
    name: prometheus
    state: started
    enabled: yes