---
- name: Keepalived package
  apt:
    name: keepalived

- name: Keepalived config
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify:
    - Restart Keepalived
  
- name: Download Keepalived exporter
  unarchive:
    src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.1.0/keepalived-exporter-1.1.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Move service file
  command: cp /usr/local/bin/keepalived-exporter-1.1.0.linux-amd64/keepalived-exporter /usr/local/bin/.

- name: Servisizing
  template:
    src: prometheus-keepalived-exporter.service.j2
    dest: /etc/systemd/system/prometheus-keepalived-exporter.service
  notify:
    - Systemctl daemon-reload
    - Restart keepalived-exporter