---
- name: Mysqld exporter package
  apt:
    name: prometheus-mysqld-exporter

- name: File for config (if i pre-create it, mysql-exporter does not show error on first run)
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: '755'
    force: no
  notify:
    - Restart mysqld-exporter

- name: Pause
  pause:
    seconds: 5

- name: Mysqld config (in case changed)
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify:
    - Restart mysqld-exporter

- name: Pause
  pause:
    seconds: 5

- name: Mysql exporter user
  mysql_user:
    name: exporter
    password: "{{ mysql_exporter_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
  no_log: True

- name: Enabled mysqld-exporter
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes