---
- name: Backup user
  user:
    name: backup
    password: "$6$eAPoFxG4BHwgQNjw$JY2QJhYHx8z44/w0ENI.kXawiG3.vQ0lcubBMGH/54oulhAvvbK.lfiN5sVVggnUzxNcKoyc6XWgHXT27ezDh0"
    shell: /bin/bash
    state: present
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/backup/.ssh/id_rsa