{
 "title": "Main Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory [VM-1]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_Active{instance=\"vm-1.julian.exam:9100\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory [VM-2]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_Active{instance=\"vm-2.julian.exam:9100\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory [VM-3]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_Active{instance=\"vm-3.julian.exam:9100\"}[5m])"
    }
   ]
  },
  {
   "title": "CPU Load [VM-1]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "CPU%" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu{mode=\"user\",instance=\"vm-1.julian.exam:9100\"}[1m]) * 100 * 2"
    }
   ]
  },
  {
   "title": "CPU Load [VM-2]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "CPU %" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu{mode=\"user\",instance=\"vm-2.julian.exam:9100\"}[1m]) * 100 * 2"
    }
   ]
  },
  {
   "title": "CPU Load [VM-3]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "CPU %" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu{mode=\"user\",instance=\"vm-3.julian.exam:9100\"}[1m]) * 100 * 2"
    }
   ]
  },
  {
   "title": "Bind slave 1 - resolver queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bind_resolver_queries_total{instance=\"bind-slave1.julian.exam:9119\", job=\"bind\"}"
    }
   ]
  },
  {
   "title": "Bind slave 2 - resolver queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bind_resolver_queries_total{instance=\"bind-slave2.julian.exam:9119\", job=\"bind\"}"
    }
   ]
  },
  {
   "title": "MySQL Master status queries / 10m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=\"db.julian.exam:9104\",job=\"mysql\"}[10m])"
    }
   ]
  },
  {
   "title": "MySQL Replication status queries / 10m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=\"db-repl.julian.exam:9104\",job=\"mysql\"}[10m])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bind Master",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"ns.julian.exam:9119\", job=\"bind\"}"
    }
   ]
  },
  {
   "title": "Bind Slave 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"bind-slave1.julian.exam:9119\", job=\"bind\"}"
    }
   ]
  },
  {
   "title": "Bind Slave 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"bind-slave2.julian.exam:9119\", job=\"bind\"}"
    }
   ]
  },
  {
   "title": "MySQL Master",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"db.julian.exam:9104\",job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "MySQL Replication",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"db-repl.julian.exam:9104\",job=\"mysql\"}"
    }
   ]
  }
 ]
}