{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MainDB_READONLY",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=\"db.julian.exam:9104\"}"
    }
   ]
  },
  {
   "title": "MainDB_READONLY",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=\"db-repl.julian.exam:9104\",job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "MySQL Master Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"db.julian.exam:9104\"}"
    }
   ]
  },
  {
   "title": "MySQL Replication Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"db-repl.julian.exam:9104\",job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "MySQL Master ID",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{instance=\"db.julian.exam:9104\"}"
    }
   ]
  },
  {
   "title": "MySQL Replication ID",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{instance=\"db-repl.julian.exam:9104\",job=\"mysql\"}"
    }
   ]
  }
 ]
}