---
- name: Node exporter package
  apt:
    name: 
      - prometheus-node-exporter
      - nginx
    update_cache: yes

- name: Installing nginx
  apt: 
    name: nginx 
    state: latest

- name: Ensure nginx started
  service:
    name: nginx
    state: started
    enabled: yes