{
 "title": "HAProxy / Keepalived",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Web-1 / Vrrp state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"web1.julprom.jd:9165\"}"
    }
   ]
  },
  {
   "title": "Web-2 / Vrrp state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"web2.julprom.jd:9165\"}"
    }
   ]
  },
  {
   "title": "VM-1:1",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{backend=\"agama_lb\",instance=\"web1.julprom.jd:9101\",job=\"haproxy\",server=\"vm-1\"}"
    }
   ]
  },
  {
   "title": "VM-1:2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{backend=\"agama_lb\",instance=\"web1.julprom.jd:9101\",job=\"haproxy\", server=\"vm-2\"}"
    }
   ]
  },
  {
   "title": "VM-2:1",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{backend=\"agama_lb\",instance=\"web2.julprom.jd:9101\",job=\"haproxy\",server=\"vm-1\"}"
    }
   ]
  },
  {
   "title": "VM-2:2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{backend=\"agama_lb\",instance=\"web2.julprom.jd:9101\",job=\"haproxy\",server=\"vm-2\"}"
    }
   ]
  },
  {
   "title": "Web-1 [HAProxy UP]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"web1.julprom.jd:9101\", job=\"haproxy\"}"
    }
   ]
  },
  {
   "title": "Web-2 [HAProxy UP]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"web2.julprom.jd:9101\", job=\"haproxy\"}"
    }
   ]
  }
 ]
}