{
 "title": "Dash2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory [VM-1]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_Active{instance=\"vm-1.julprom.jd:9100\"}[10m])"
    }
   ]
  },
  {
   "title": "Memory [VM-2]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_Active{instance=\"vm-2.julprom.jd:9100\"}[10m])"
    }
   ]
  },
  {
   "title": "CPU Load [VM-1]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "CPU%" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu{mode=\"user\",instance=\"vm-1.julprom.jd:9100\"}[10m]) * 100 * 2"
    }
   ]
  },
  {
   "title": "CPU Load [VM-2]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "CPU %" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu{mode=\"user\",instance=\"vm-2.julprom.jd:9100\"}[10m]) * 100 * 2"
    }
   ]
  },
  {
   "title": "Bind resolver queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"ns.julprom.jd:9119\",job=\"bind\",view=\"_default\"}[5m])"
    }
   ]
  },
  {
   "title": "Bind slave resolver queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"bind-slave.julprom.jd:9119\",job=\"bind-slave\",view=\"_default\"}[5m])"
    }
   ]
  },
  {
   "title": "Nginx http requests total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_http_requests_total" }
   ]
  },
  {
   "title": "Mysql status queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_global_status_queries" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Bind",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"ns.julprom.jd:9119\", job=\"bind\"}"
    }
   ]
  },
  {
   "title": "Bind-Slave",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"bind-slave.julprom.jd:9119\", job=\"bind-slave\"}"
    }
   ]
  }
 ]
}