{
 "title": "HAProxy / Keepalived",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Web-1 / Vrrp state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"web1.julprom.jd:9165\"}"
    }
   ]
  },
  {
   "title": "Web-2 / Vrrp state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"web2.julprom.jd:9165\"}"
    }
   ]
  },
  {
   "title": "Web-1, agama_lb:backend",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{backend=\"agama_lb\",instance=\"web1.julprom.jd:9101\",job=\"haproxy\"}"
    }
   ]
  },
  {
   "title": "Web-2, agama_lb:backend",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{backend=\"agama_lb\",instance=\"web2.julprom.jd:9101\",job=\"haproxy\"}"
    }
   ]
  },
  {
   "title": "Web-1 [HAProxy UP]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"web1.julprom.jd:9101\", job=\"haproxy\"}"
    }
   ]
  },
  {
   "title": "Web-2 [HAProxy UP]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"web2.julprom.jd:9101\", job=\"haproxy\"}"
    }
   ]
  }
 ]
}