---
- name: Collect info about all VMs
  hosts: all
  become: yes
  roles:
    - init
    - users

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind
    - bind_exporter
  tags:
    - bind

- name: Resolvers (etc/resolv.conf - resolvers etc. etc.)
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - hosts_dns
  tags:
    - resolver

- name: Prometheus
  hosts: prometheus_server
  become: yes
  gather_facts: no
  roles:
    - prometheus
  tags:
    - prometheus

- name: Grafana
  hosts: grafana
  become: yes
  gather_facts: no
  roles:
    - grafana
  tags:
    - grafana

- name: General monitoring
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - rsyslog
  tags:
    - rsyslog
    - rsys

- name: Reverse proxy
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - reverse_proxy
    - nginx_exporter
  tags:
    - proxy

- name: Docker
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - docker
    - agama_docker
  tags:
    - docker


- name: HAProxy
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - haproxy
  tags:
    - haproxy

- name: Keepalived
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - keepalived
  tags:
    - keepalived
